name: _Tag
on:
  pull_request:
    types: [closed]
    branches:
      - qcom-next-staging-test
    
jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Tag
        run: |
          set -x
          BRANCH_NAME="qcom-next-test"
          CURRVER=$(awk '/^VERSION =/ {v=$3} /^PATCHLEVEL =/ {p=$3} /^EXTRAVERSION =/ {e=$3} END {print v "." p e}' Makefile)
          TAG_NAME="${BRANCH_NAME}-${CURRVER}-$(date +%Y%m%d)"
          git push origin qcom-next-staging-test:qcom-next-test -f
          #TAG_NAME="v$(date +'%Y.%m.%d.%H%M%S')"
          git checkout qcom-next-test
          git pull
          git tag $TAG_NAME
          git push origin $TAG_NAME
